name: Run Rest Assured Test Cases

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "18"
          distribution: 'temurin'
          cache: maven
      - run: mvn clean test

